<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>DJavaWeb</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <modules>
        <module>maven-project01</module>
        <module>maven-project02</module>
        <module>maven-projectA</module>
        <module>maven-projectB</module>
        <module>maven-projectC</module>
        <module>springboot-web-quickstart</module>
        <module>http-server-demo</module>
        <module>springboot-web-quickstart2</module>
        <module>springboot-web-req-resp</module>
        <module>springboot-mybatis-quickstart</module>
        <module>springboot-mybatis-crud</module>
        <module>tlias-web-management</module>
    </modules>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

</project>